### ISSUE TITLE
Add dvipdfmx package option

### ISSUE THREAD

**Issue by aminophen** [davidcarlisle/geometry#1]
It would be nice if geometry understand [dvipdfmx] option; simply adding

\DeclareOption{dvipdfmx}{\ExecuteOptions{dvipdfm}}

would be enough.

**Comment by aminophen** [comment]
Version 2018/04/16 v5.8 works fine, thanks!

**Comment by davidcarlisle** [comment]
jfbu reported via mail:

> but the pdf documentation was not updated about new
> dvipdfmx and xdvipdfmx, as far as I can tell,
> searching "dvipdfmx" in pdf viewer brings me
> to the commented source code. Even the code comments
> do not make it completely clear.

I should add a note about the aliases to the user-documentation part describing package options.
