### ISSUE TITLE
\geometry{paperwidth=10mm, paperheight=5mm} % works wrong, and creates multiple pages

### ISSUE THREAD

**Issue by wshppi** [davidcarlisle/geometry#5]
I figured out that small paper height < 6mm cause multiple output pages.

Please try the following example and compare
\geometry{paperwidth=10mm, paperheight=6mm} % works 
and
\geometry{paperwidth=10mm, paperheight=5mm} % works wrong, and creates multiple pages

\documentclass[10pt]{article}
\usepackage{geometry}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\geometry{paperwidth=10mm, paperheight=6mm} % works 
% \geometry{paperwidth=10mm, paperheight=5mm} % works wrong, and creates multiple pages

\begin{document}
\noindent\tiny Hello
\end{document}

**Comment by davidcarlisle** [comment]
This is not really related to the geometry package, you get essentially the same from

```
\documentclass[10pt]{article}

\setlength\textheight{9.5pt}
\begin{document}
\noindent\tiny Hello
\end{document}
```

The default value of `\topskip`  (the position of the first line) is 10pt so if you set `\textheight` to less than that then the page constraints are not achievable and it is impossible to place any text on the page without an overfull box.

**Comment by wshppi** [comment]
Thank you David, for pointing me to the TeX output log file.
I tried to use very small paper size in the millimeter range for creating very small lables.
Now I will go other ways, e.g. using the textpos package.

Thanks,
Werner Simbuerger

**Comment by davidcarlisle** [comment]
@wshppi  the standalone package may be what you want here it makes the page clipped to the size of teh content you provide
